# OD-Database server settings
server:
  # Connection URL
  url: http://od-db.mine.terorie.com/api
  # Server auth token
  token:

# Log output settings
output:
  # Crawl statistics
  crawl_stats: 1s
  # CPU/RAM/Job queue stats
  resource_stats: 10s
  # More output? (Every listed dir)
  verbose: false

# Crawler settings
crawl:
  # Number of sites that can be
  # processed at once
  tasks: 300
  # Number of connections per site
  connections: 20
  # How often to retry getting data
  # from the site before giving up
  retries: 5
  # Time before discarding a network request
  timeout: 10s
